# Site settings
title: hola
email: coburn.d.berry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A programming blog so I can show off how many books
 I've read and maybe get some utility out of pointless 
 Saturday morning code experiments.
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: crododile
github_username:  crododile

# Build settings
markdown: kramdown
